### ISSUE TITLE
Design Code Review 1

### ISSUE THREAD

**Issue by Amatheia** [glenndog/JobLeadAggregator#2]
# Design/Code Review 1

#### Reviewer: April

|Category|Criteria|Rating/Comments|
|--------|---------|---------------|
|**Problem Statement**|Does it exist?| Yes |
|Does the problem statement accurately describe project purpose?| Yes |
|Is the problem statement professional? Think of prospective employers viewing this as part of the developer's portfolio.| Yes |
|What is good?| Explains the issue well, what the app will do |
|What could be improved?| break it up into Problem and Solution |
|**Design Documentation**|Does it exist?| Yes |
|Is the navigation/flow through the application logical and easy to use?| pngs are numbered |
|Is the order in which the fields are displayed and form fields entered logical and easy to use?| see what could be improved notes|
|What data is missing?| Needs job search criteria page; add user; edit user |
|Is there data that is not used?| add user, edit user; search criteria |
|What is good?| nice start to a well-developed idea |
|What could be improved?| Sign in Page - move register to a different page; job search and list are confusing - make notes about what differentiates these; new page titles so we're not confused what the page offers |
|**Data model**|Does it exist?| No |
|Is everything on the screens represented in the model?| |
|Does the model represent good database design? | |
|What is good?| |
|What could be better?| |
|**Additional design documents**| No | a flow diagram that shows how all the pages connect and work together |
|**Application structure in IntelliJ**|Does it exist?| No |
|Is the structure correct for a Maven project?| |
|Are packages and classs appropriately named?   | |
|Other comments/notes?| |
|**JSPs**|Do they exist?| No |
|Is templating used (for example, header.jsp, footer.jsp, etc.)?| |
|Is there business logic mixed in the JSPs?| |
|CSS?| |
|Other comments/notes?| |
|**Entities/DAOs/Controllers**|Do they exist?| No |
|**Java code quality**|Are methods single-purpose?| |
|Are classes appropriately-sized classes (no monster classes)?| |
|Are the same lines of code repeated at all?| | 
|Do any classes perform very similar functions that could be candidates for super/subclass relationships?| |
|Are any values hard-coded that should be in a properties file?| |
|Are variable names descriptive?| |
|Are there many branches or loops that could be simplified or broken up into smaller methods?| |
|Do the DAOs use Hibernate? No hard-coded sql!| |
|Other comments/notes?| |
|**Logging**|Has log4J been added?| No |
|Are there logging statements in the code?| |
|Are appropriate logging levels used? Info, debug, error, for example.| |
|Are there any System.out.printlns in the code?| |
|Other comments/notes?| |
|**Unit Tests**|Do they exist?| No |
|Do the tests pass?| |
|What is the current code coverage?| |
|Is each test truly a unit test or are they functional tests?| |
|Other comments/notes?| |
|**Web Service/API integration**|Has a web service/api been selected? | Yes |
|What web services/apis might work well with this application?| JSON |
|**Independent research topic**| Has a topic been selected?| Yes |
|What topic/s might fit well in this application?| Jackson |

**Comment by pawaitemadisoncollege** [comment]
This formatting got lost a bit, can you fix so it's in pretty table form?

**Comment by Amatheia** [comment]
Yeah, I used MacDown and it looked fine. Not sure what happened.

________________________________

**Comment by Amatheia** [comment]
Fixed.

**Comment by pawaitemadisoncollege** [comment]
Good feedback so far. Can you also update if something doesn't exist with a "no" or n/a? Thanks much!

**Comment by Amatheia** [comment]
Updated.

**Comment by pawaitemadisoncollege** [comment]
Thank you!
