### ISSUE TITLE
Instructor Feedback Week 5 - Checkpoint 2

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [glenndog/JobLeadAggregator#4]
I like that you are keeping your sql in git. 

- [x] A note about issues/feedback. Please add an "X" to check off the checkboxes to indicate you have completed the work or responded to the questions. When all done, then you can close the issue. See example below:
- [x] A completed task.
- [x] Something to keep in mind in general - if there were an error in a DAO, what would the user experience be? You might consider throwing an exception (you can create your own exceptions) that the controller would catch and then route the user to a friendly-looking error page.
- [x] Remember to close session after opening in the UserDao.
- [x] Thanks for the Swedish Chef reference in the UserDaoTest - made me smile.

**Comment by glenndog** [comment]
Will implement that soon.
