### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Tubakien** [glenndog/JobLeadAggregator#5]
# Design/Code Review 2

#### Reviewer: Kien Warren

|Category|Criteria|Analysis/Comments|
|--------|---------|---------------|
|**Running application**|| |
||Describe the application functionality that has been built and is working.| |
||What is good?| No link to project |
||What could be improved?| No link to project |
|**Unit Tests**|| |
||What are the code coverage statistics?| 0% class,  0% Method, 0% Line  | 
||Are @Before/@BeforeClass/@After/@AfterClass used to reduce redundant code?| Before: yes. After: kind of.| 
|**JSPs**|| |
|| Is templating used to eliminate rundandant code(for example, header.jsp, footer.jsp, etc.)| Yes. |
||What is good?| Templating. It looks like you have login pages implemented |
||What could be improved?|  |
|**Code quality**|| |
||Are methods single-purpose?|The methods are single purpose.|
||Are classes appropriately-sized classes (no monster classes)?| The classes are appropriately sized.|
||Are the same lines of code repeated at all?| In the UserDao.java when the session is closed and the transactions are committed. But it's only 2 lines. | 
||Do any classes perform very similar functions that could be candidates for super/subclass relationships?| No |
||Are any values hard-coded that should be in a properties file?| No |
||Are variable names descriptive?| Yes |
||Are there many branches or loops that could be simplified or broken up into smaller methods?| No |
||Do the DAOs use Hibernate? No hard-coded sql!| Yes |
||Has log4J been added?| Yes |
||Are there logging statements in the code?| Yes |
||Are appropriate logging levels used? Info, debug, error, for example.| Yes |
||Are there any System.out.printlns in the code?| No |
||Other comments/notes?| Yes |
|**Web Service/API integration**|Which web service/api is being used? | jQuery |
||Is the integration built?| from what I can tell...yes |
|| If so, evaluate the integration code. What is good? What could use improvement?
|**Independent research topic**| What is the developer's independent research topic?| jsoup, |
||Has the topic been implemented in the project?| I don't think so |
||If so, evaluate the implementation. What is good? What could use improvement?| |
|**Key takeaways**|List at least 3 things you learned while reviewing this project that will help you in your own project.| I should not use hard-coded SQL. I should catch up. I should template more code in jsps|

**Comment by pawaitemadisoncollege** [comment]
Can you please fix up the formatting here - adding a space between the leading || should do it. Thanks!

**Comment by pawaitemadisoncollege** [comment]
Please take some time to work with the developer to understand what functionality has been implemented so far.  Jquery is not an web service/api - perhaps that is the independent research topic?
