### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by RoderickMonforte** [glenndog/JobLeadAggregator#6]
# Design/Code Review 2

#### Reviewer: Roderick Monforte

|Category|Criteria|Analysis/Comments|
|--------|---------|---------------|
|**Running application**|| |
||Describe the application functionality that has been built and is working.| There was no link provided to execute program in AWS.|
||What is good?| NA|
||What could be improved?| NA|
|**Unit Tests**|| |
||What are the code coverage statistics?| There is one DAO test.| 
||Are @Before/@BeforeClass/@After/@AfterClass used to reduce redundant code?|Yes | 
|**JSPs**|| |
|| Is templating used to eliminate rundandant code(for example, header.jsp, footer.jsp, etc.)| Yes|
||What is good?| Yes |
||What could be improved?|None  |
|**Code quality**|| |
||Are methods single-purpose?|Yes|
||Are classes appropriately-sized classes (no monster classes)?| Yes |
||Are the same lines of code repeated at all?| None| 
||Do any classes perform very similar functions that could be candidates for super/subclass relationships?| None|
||Are any values hard-coded that should be in a properties file?| None|
||Are variable names descriptive?|Yes |
||Are there many branches or loops that could be simplified or broken up into smaller methods?|None |
||Do the DAOs use Hibernate? No hard-coded sql!| None|
||Has log4J been added?|Yes |
||Are there logging statements in the code?| Yes|
||Are appropriate logging levels used? Info, debug, error, for example.| Yes |
||Are there any System.out.printlns in the code?| None|
||Other comments/notes?| |
|**Web Service/API integration**|Which web service/api is being used? | I did not see any yet.|
||Is the integration built?| Don't know what is integration.|
|| If so, evaluate the integration code. What is good? What could use improvement?
|**Independent research topic**| What is the developer's independent research topic?| Did not specify|
||Has the topic been implemented in the project?| Did not see any. |
||If so, evaluate the implementation. What is good? What could use improvement?|NA |
|**Key takeaways**|List at least 3 things you learned while reviewing this project that will help you in your own project.|I need to do more testing, I need to specify my research topic and I need to code my web service|

**Comment by pawaitemadisoncollege** [comment]
Please take a look at the formatting here.  This review appears incomplete - can you add in the functionality that is currently implemented? Log in, add account, search? Compare what works to what is listed in the application problem statement.

**Comment by glenndog** [comment]
To be fair, there wasn't much to go on.
