### ISSUE TITLE
Instructor Feedback Week 13

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [glenndog/JobLeadAggregator#7]
- [x] Is this deployed to AWS? If so, could you add a link to the list of individual projects and let me know when it's updated?  

The following are from a review of the code only, not the running application. 
- [x] Remember to include exception handling for hibernate exceptions in the Daos, - either catch and handle or log and throw to the next layer. 
- [x] Consider using an abstract/generic dao to minimize redundancy in the daos which will all likely getById, getAll, deleteById, upDateById, etc.  This is a [good article with sample code](https://www.ibm.com/developerworks/library/j-genericdao/). Be sure to ignore/skip over any of the Spring details. 
- [x] I like where you are headed with providing your main application functionality as a Restful api.  
- [x] Looks like you have some work to do yet, what is your plan for the next couple weeks?

**Comment by glenndog** [comment]
" Remember to include exception handling for hibernate exceptions in the Daos, - either catch and handle or log and throw to the next layer."

My hibernate mapping of the relationship between user and search is working suboptimally...and kinda highlights that point.

**Comment by glenndog** [comment]
Re: Plan for the next 13 days. 

Add the service for USJobPlace (GitHubJobs is already working).

Get the search aggregation working. By this I mean where user does a search and gets a unified result set from calls to the 2 job services, and display that list of the job results to the user (ie. includes a UI). 

2. Add ability for the user to save the search results. (incl a UI for that)

3. See what kind of time is left, a list of the saved searches would be the next thing if there's time.

**Comment by glenndog** [comment]
OK, I got the USJobPlace service (had it before the review, brain fart). Just finished the 'pilot' of generic dao. Which was not on the list but it's pretty important if one wants to DRY. 

Substeps: make daos for all my entities/tables.

Then follow my plan from above.
